/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package holaventanatuneadamvc.vistaHolaV;

/**
 *
 * @author Sergio Teacher
 */
public class MiPanelTuneadoHolaV extends javax.swing.JPanel {

    /**
     * Creates new form MiPanelTuneadoHolaV
     */
    public MiPanelTuneadoHolaV() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        TextFieldCampo = new javax.swing.JTextField();
        BtnValidar = new javax.swing.JButton();

        jLabel1.setText("Campo: ");
        add(jLabel1);

        TextFieldCampo.setColumns(10);
        add(TextFieldCampo);

        BtnValidar.setText("Validar");
        add(BtnValidar);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnValidar;
    private javax.swing.JTextField TextFieldCampo;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
