/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package holaventanatuneadamvc.vistaHolaV;

import java.awt.event.ActionListener;

/**
 *
 * @author Sergio Teacher
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        this.setBounds(0, 0, 300, 180);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlabelNorte = new javax.swing.JLabel();
        jLabelSur = new javax.swing.JLabel();
        jPanelCentral = new javax.swing.JPanel();
        miPanelTuneadoHolaV1 = new holaventanatuneadamvc.vistaHolaV.MiPanelTuneadoHolaV();
        jPanelParaRecolocar = new javax.swing.JPanel();
        BtnOk = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Hola Ventana Tuneada");

        jlabelNorte.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlabelNorte.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlabelNorte.setText("Hola mundo");
        getContentPane().add(jlabelNorte, java.awt.BorderLayout.PAGE_START);

        jLabelSur.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelSur.setText("?");
        getContentPane().add(jLabelSur, java.awt.BorderLayout.PAGE_END);

        jPanelCentral.setLayout(new javax.swing.BoxLayout(jPanelCentral, javax.swing.BoxLayout.Y_AXIS));
        jPanelCentral.add(miPanelTuneadoHolaV1);

        jPanelParaRecolocar.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        BtnOk.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        BtnOk.setText("Ok!");
        jPanelParaRecolocar.add(BtnOk);

        jPanelCentral.add(jPanelParaRecolocar);

        getContentPane().add(jPanelCentral, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnOk;
    private javax.swing.JLabel jLabelSur;
    private javax.swing.JPanel jPanelCentral;
    private javax.swing.JPanel jPanelParaRecolocar;
    private javax.swing.JLabel jlabelNorte;
    private holaventanatuneadamvc.vistaHolaV.MiPanelTuneadoHolaV miPanelTuneadoHolaV1;
    // End of variables declaration//GEN-END:variables

    /**
    * Un truco para actuar sobre el Jlabel
    */
    public void escribeTxtEstado(String s) {                                      
        //jLabelSur.setText("  Hola holita");
        jLabelSur.setText(s);
    }  

    /**
    * Doy el control de escuchar al botón Ok!
    */
    public void addActionListenerBtnOk(ActionListener l){
        BtnOk.addActionListener(l);
    }
    /**
    * Doy el control de escuchar al botón Validar
    * pero como este está dentro de un panel tuneado
    * en realidad doy el control de escuchar al "panel"
    * y este en su código tiene un método para el botón Validar
    *
    * Hay que tener en cuenta que es un objeto dentro de un objeto
    * uno coge la señal y se la pasa al otro
    */
    public void addActionListenerMiPanelTuneadoHolaV(ActionListener l){
        miPanelTuneadoHolaV1.addActionListenerBtnValidar(l);
    }

    /**
    * Obtengo el String y lo paso
    */
    public String getTextFieldCampo(){
        return miPanelTuneadoHolaV1.getTextFieldCampoTuneado();
    }
    /**
    * Igual, ahora meto el String a la caja de texto del panel tuneado
    */
    public void setTextFieldCampo(String Micadena) {
        miPanelTuneadoHolaV1.setTextFieldCampoTuneado(Micadena);
    }

}
